version: "3"
services:
  mysql:
    image: mysql/mysql-server:5.7
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - myrailsapp_bundle:/app/vendor/bundle
      - myrailsapp_node_modules:/app/node_modules
  
volumes:
  mysql-data:
    driver: local
  myrailsapp_bundle:
    driver: local
  myrailsapp_node_modules:
    driver: local
